#!/bin/bash
#set -ix

BRANCH=$1 # ffmdev, ffmstable, ffmtest...
IMAGETYPE=${2:-factory} #sysupgrade, factory
KEEPVERS=${3:-3} # keep last 3 versions, remove older ones

runonserver ()
{
	ssh -p 2204 -C ffmfiles@jenkins.ffm.freifunk.net "$@"
}

firmwareget()
{
	rm -f /var/www/jenkins_files/ffm/firmware/${BRANCH//ffm}/${IMAGETYPE}/*
	scp -P 2204 "ffmfiles@jenkins.ffm.freifunk.net:/var/www/jenkins_files/ffm/firmware/${BRANCH//ffm}/${IMAGETYPE}/*${rver}*" /var/www/files/firmware/${BRANCH//ffm}/${IMAGETYPE}/
	[[ $IMAGETYPE != "factory" ]] && scp -P 2204 "ffmfiles@jenkins.ffm.freifunk.net:/var/www/jenkins_files/ffm/firmware/${BRANCH//ffm}/${IMAGETYPE}/*manifest" /var/www/files/firmware/${BRANCH//ffm}/${IMAGETYPE}/
}


# determine current version of the branch
cver=$(ls /var/www/files/firmware/${BRANCH//ffm}/${IMAGETYPE}/|awk -F"${BRANCH}-" '{print $2}'|grep tp-link|awk -F '-tp-link' '{print $1}'|sort -u -t.  -k1,1n -k 2,2n|tail -n1)

rver=$(runonserver "ls /var/www/jenkins_files/ffm/firmware/${BRANCH//ffm}/${IMAGETYPE}"|awk -F"${BRANCH}-" '{print $2}'|grep tp-link|awk -F '-tp-link' '{print $1}'|sort -u -t.  -k1,1n -k 2,2n|tail -n1)

if [[ -z $cver ]]
then
firmwareget
exit 0
fi

if [[ ${cver%.*} -le ${rver%.*} ]]
then
	if [[ ${cver%.*} -eq ${rver%.*} ]]
	then
		if [[ ${cver#*.} -lt ${rver#*.} ]]
		then
			# download new version
			firmwareget
		fi
	else
	# download new version
	firmwareget
	fi
fi

# TODO nur die letzten $KEEPVERS-Version behalten
kvers=( $(ls /var/www/files/firmware/${BRANCH//ffm}/${IMAGETYPE}/|awk -F"${BRANCH}-" '{print $2}'|grep tp-link|awk -F '-tp-link' '{print $1}'|sort -u -t.  -k1,1n -k 2,2n|tail -n$KEEPVERS) )

for img in /var/www/files/firmware/${BRANCH//ffm}/${IMAGETYPE}/*.bin
do
	match=0
	for i in ${kvers[@]}
	do
		echo "$img" | grep -q ${i##*/} && match=1
	done
	if [[ $match -eq 0 ]]
	then
		rm "$img"
	fi
done

