#!/bin/bash
#killall alfred 2>/dev/null
#killall batadv-vis 2>/dev/null

source $(pwd)/env
echo $FIF $BATIF $fastdserver
/sbin/ifconfig $FIF hw ether 02:ff:0f:$(printf %02d ${fastdserver}):7d:12 up
/sbin/ip link set dev $FIF up
/sbin/ip link set dev $BATIF up

/usr/sbin/batctl -m $BATIF if add $FIF
/usr/sbin/batctl -m $BATIF it 5000
/sbin/ifconfig $BATIF up
/sbin/ifconfig $FIF up
